# apiVersion: v1

# kind: Pod

# metadata:
#   name: nginx

# spec:
#   containers:
#     - name: echo

#       image: registry.cluster.wik.cloud/public/echo

#       ports:
#         - containerPort: 8080

# apiVersion: apps/v1

# kind: ReplicaSet
# metadata:
#   name: nginx
#   labels:
#     app: test
#     tier: nginx
# spec:
#   replicas: 4
#   selector:
#     matchLabels:
#       tier: nginx
#   template:
#     metadata:
#       labels:
#         tier: nginx
#     spec:
#       containers:
#         - name: echo
#           image: registry.cluster.wik.cloud/public/echo

#           ports:
#             - containerPort: 8080

apiVersion: apps/v1

kind: Deployment
metadata:
  name: nginx
  labels:
    app: test
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  selector:
    matchLabels:
      tier: nginx
  template:
    metadata:
      labels:
        tier: nginx
    spec:
      containers:
        - name: echo
          image: registry.cluster.wik.cloud/public/echo

          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 90
      targetPort: 8080
